export const seedPosts = [
  {
    "id": "seed_hilton_4",
    "brand": "Hilton",
    "date": "2026-02-01",
    "title": "Friends Valentin's Dinner party colaboracion",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 24000,
    "likes": 242,
    "comments": 5,
    "shares": 26,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_5",
    "brand": "Hilton",
    "date": "2026-02-03",
    "title": "san valentin",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 5486,
    "likes": 47,
    "comments": 1,
    "shares": 5,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_6",
    "brand": "Hilton",
    "date": "2026-02-03",
    "title": "Carnaval",
    "format": "Reel",
    "category": "Hospedaje",
    "views": 9557,
    "likes": 0,
    "comments": 3,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_7",
    "brand": "Hilton",
    "date": "2026-02-05",
    "title": "Madrid Fusión - chef",
    "format": "Carrusel",
    "category": "Otros",
    "views": 0,
    "likes": 438,
    "comments": 38,
    "shares": 9,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_8",
    "brand": "Hilton",
    "date": "2026-02-06",
    "title": "WQ radio - san valentin en hilton",
    "format": "Reel",
    "category": "Otros",
    "views": 4975,
    "likes": 34,
    "comments": 0,
    "shares": 13,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_9",
    "brand": "Hilton",
    "date": "2026-02-06",
    "title": "Menú de san valentin",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 23,
    "comments": 1,
    "shares": 5,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_10",
    "brand": "Hilton",
    "date": "2026-02-06",
    "title": "WQ radio - Noches de tributo al amor y desamor -  san valentin en hilton",
    "format": "Carrusel",
    "category": "Otros",
    "views": 0,
    "likes": 24,
    "comments": 0,
    "shares": 7,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_11",
    "brand": "Hilton",
    "date": "2026-02-07",
    "title": "san valentin",
    "format": "Reel",
    "category": "Hospedaje",
    "views": 3431,
    "likes": 44,
    "comments": 4,
    "shares": 10,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_12",
    "brand": "Hilton",
    "date": "2026-02-08",
    "title": "Picnic Love 2 Go - San Valenti",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 5587,
    "likes": 48,
    "comments": 1,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_13",
    "brand": "Hilton",
    "date": "2026-02-09",
    "title": "Cenas - San Valentin",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 44,
    "comments": 4,
    "shares": 4,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_14",
    "brand": "Hilton",
    "date": "2026-02-10",
    "title": "Noches de tributo al amor y desamor - san valentin",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 19,
    "comments": 2,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_15",
    "brand": "Hilton",
    "date": "2026-02-10",
    "title": "san valentin (te buffet-cenabuffet-love beats(coteleria))",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 32,
    "comments": 2,
    "shares": 6,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_16",
    "brand": "Hilton",
    "date": "2026-02-11",
    "title": "Cenas - San Valentin - menú frances",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 10800,
    "likes": 98,
    "comments": 1,
    "shares": 14,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_17",
    "brand": "Hilton",
    "date": "2026-02-11",
    "title": "Té buffet con musica en vivo - san valentin",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 41,
    "comments": 0,
    "shares": 4,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_18",
    "brand": "Hilton",
    "date": "2026-02-12",
    "title": "Graduación",
    "format": "Reel",
    "category": "Eventos",
    "views": 16800,
    "likes": 352,
    "comments": 10,
    "shares": 71,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_19",
    "brand": "Hilton",
    "date": "2026-02-13",
    "title": "Sushi Extravaganza ‘All You Can Eat’ - san valentin",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 0,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_20",
    "brand": "Hilton",
    "date": "2026-02-14",
    "title": "Horarios de feriado - restaurantes",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 0,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_21",
    "brand": "Hilton",
    "date": "2026-02-15",
    "title": "5 razones para pasar el feriado en Hilton",
    "format": "Carrusel",
    "category": "Hospedaje",
    "views": 0,
    "likes": 0,
    "comments": 2,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_22",
    "brand": "Hilton",
    "date": "2026-02-17",
    "title": "Fanesca",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 48,
    "comments": 0,
    "shares": 11,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_23",
    "brand": "Hilton",
    "date": "2026-02-19",
    "title": "Vive la previa y after del concierto de alejandro sanz en hilton",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 68,
    "comments": 4,
    "shares": 36,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_24",
    "brand": "Hilton",
    "date": "2026-02-22",
    "title": "Celebremos el Día de la mujer",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 103,
    "comments": 4,
    "shares": 599,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_25",
    "brand": "Hilton",
    "date": "2026-02-23",
    "title": "Noches de miercoles",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 0,
    "comments": 7,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_26",
    "brand": "Hilton",
    "date": "2026-02-24",
    "title": "Fanesca",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 0,
    "comments": 1,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_27",
    "brand": "Hilton",
    "date": "2026-02-25",
    "title": "World Bartender Day",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 3160,
    "likes": 0,
    "comments": 3,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_28",
    "brand": "Hilton",
    "date": "2026-02-26",
    "title": "¿Estás de cumpleaños?",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 185,
    "comments": 16,
    "shares": 16,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_29",
    "brand": "Hilton",
    "date": "2026-02-27",
    "title": "Chito vera vs david martinez | ven a atrium disfruta de la pelea",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 0,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_30",
    "brand": "Hilton",
    "date": "2026-03-01",
    "title": "Hightlights marzo y abril",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 193,
    "comments": 4,
    "shares": 31,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_31",
    "brand": "Hilton",
    "date": "2026-03-02",
    "title": "Celebremos el Día de la mujer",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 0,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_32",
    "brand": "Hilton",
    "date": "2026-03-03",
    "title": "promo summer fitness",
    "format": "Carrusel",
    "category": "Hospedaje",
    "views": 0,
    "likes": 0,
    "comments": 12,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_33",
    "brand": "Hilton",
    "date": "2026-03-04",
    "title": "Graduación",
    "format": "Reel",
    "category": "Eventos",
    "views": 14800,
    "likes": 306,
    "comments": 7,
    "shares": 52,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_34",
    "brand": "Hilton",
    "date": "2026-03-05",
    "title": "Especial de cuaresma",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 0,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_35",
    "brand": "Hilton",
    "date": "2026-03-05",
    "title": "Ladies & Drinks en Atrium Bar. - Dia de la mujer",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 0,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_36",
    "brand": "Hilton",
    "date": "2026-03-08",
    "title": "Feliz día de la mujer!",
    "format": "Post",
    "category": "Otros",
    "views": 0,
    "likes": 0,
    "comments": 1,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_37",
    "brand": "Hilton",
    "date": "2026-03-09",
    "title": "Corner mexicano",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 44,
    "comments": 2,
    "shares": 7,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_38",
    "brand": "Hilton",
    "date": "2026-03-12",
    "title": "Sanduche Ham&Cheese",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 5239,
    "likes": 56,
    "comments": 5,
    "shares": 7,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_39",
    "brand": "Hilton",
    "date": "2026-03-13",
    "title": "Oscars en atrium",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 0,
    "comments": 2,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_40",
    "brand": "Hilton",
    "date": "2026-03-14",
    "title": "Atrium - margaritas promo",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 3426,
    "likes": 0,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_41",
    "brand": "Hilton",
    "date": "2026-03-15",
    "title": "Saint Patrick’s Day",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 0,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_42",
    "brand": "Hilton",
    "date": "2026-03-17",
    "title": "Horarios de temporales por toque de queda - restaurantes",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 0,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_43",
    "brand": "Hilton",
    "date": "2026-03-17",
    "title": "Alumerzo tematico mx",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 12400,
    "likes": 140,
    "comments": 7,
    "shares": 38,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_44",
    "brand": "Hilton",
    "date": "2026-03-18",
    "title": "WorkSpaces",
    "format": "Carrusel",
    "category": "Hospedaje",
    "views": 0,
    "likes": 0,
    "comments": 2,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_45",
    "brand": "Hilton",
    "date": "2026-03-19",
    "title": "Día de la felicidad",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 0,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_46",
    "brand": "Hilton",
    "date": "2026-03-20",
    "title": "Fanesca",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 57900,
    "likes": 0,
    "comments": 8,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_47",
    "brand": "Hilton",
    "date": "2026-03-20",
    "title": "Pasteleria de cuaresma",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 0,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_48",
    "brand": "Hilton",
    "date": "2026-03-21",
    "title": "Pool day",
    "format": "Reel",
    "category": "Hospedaje",
    "views": 3397,
    "likes": 0,
    "comments": 1,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_49",
    "brand": "Hilton",
    "date": "2026-03-22",
    "title": "Roll into Love - cena romantica",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 0,
    "comments": 1,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_50",
    "brand": "Hilton",
    "date": "2026-03-23",
    "title": "Reuben sándwich!",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 3947,
    "likes": 0,
    "comments": 3,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_51",
    "brand": "Hilton",
    "date": "2026-03-25",
    "title": "Nominacion en los World Travel Awards",
    "format": "Carrusel",
    "category": "Otros",
    "views": 0,
    "likes": 0,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_52",
    "brand": "Hilton",
    "date": "2026-03-27",
    "title": "promos de feriado",
    "format": "Reel",
    "category": "Hospedaje",
    "views": 53600,
    "likes": 0,
    "comments": 2,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_53",
    "brand": "Hilton",
    "date": "2026-03-28",
    "title": "Especial de cuaresma",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 3223,
    "likes": 0,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_54",
    "brand": "Hilton",
    "date": "2026-03-31",
    "title": "¿Estás de cumpleaños?",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 5529,
    "likes": 0,
    "comments": 5,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_55",
    "brand": "Hilton",
    "date": "2026-04-01",
    "title": "Elige tu plan favorito",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 7249,
    "likes": 0,
    "comments": 1,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_56",
    "brand": "Hilton",
    "date": "2026-04-03",
    "title": "Horarios de feriado - restaurantes",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 0,
    "comments": 1,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_57",
    "brand": "Hilton",
    "date": "2026-04-05",
    "title": "Reminder de fanesca ultimos dias",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 2769,
    "likes": 0,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_58",
    "brand": "Hilton",
    "date": "2026-04-08",
    "title": "nominados  los World Travel Awards",
    "format": "Carrusel",
    "category": "Otros",
    "views": 0,
    "likes": 0,
    "comments": 2,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_59",
    "brand": "Hilton",
    "date": "2026-04-09",
    "title": "Dia de la madre",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 95300,
    "likes": 0,
    "comments": 43,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_60",
    "brand": "Hilton",
    "date": "2026-04-10",
    "title": "Pool day",
    "format": "Carrusel",
    "category": "Hospedaje",
    "views": 0,
    "likes": 0,
    "comments": 2,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_61",
    "brand": "Hilton",
    "date": "2026-04-12",
    "title": "Corner Bistro De paris",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 0,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_62",
    "brand": "Hilton",
    "date": "2026-04-13",
    "title": "Día de la madre",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 0,
    "comments": 5,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_63",
    "brand": "Hilton",
    "date": "2026-04-14",
    "title": "Corner Bistro De paris",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 4459,
    "likes": 0,
    "comments": 2,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_64",
    "brand": "Hilton",
    "date": "2026-04-15",
    "title": "combo stangen",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 2806,
    "likes": 0,
    "comments": 4,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_65",
    "brand": "Hilton",
    "date": "2026-04-17",
    "title": "Pool day",
    "format": "Reel",
    "category": "Hospedaje",
    "views": 37900,
    "likes": 0,
    "comments": 2,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_66",
    "brand": "Hilton",
    "date": "2026-04-17",
    "title": "Promos que tiene Fresco y Limpio",
    "format": "Carrusel",
    "category": "Hospedaje",
    "views": 0,
    "likes": 0,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_67",
    "brand": "Hilton",
    "date": "2026-04-19",
    "title": "Punto de venta dia de la madre",
    "format": "Post",
    "category": "Otros",
    "views": 0,
    "likes": 0,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_68",
    "brand": "Hilton",
    "date": "2026-04-21",
    "title": "alumerzo buffet bailable dia la madre",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 0,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_69",
    "brand": "Hilton",
    "date": "2026-04-23",
    "title": "EXPERIENCIA sensorial",
    "format": "Reel",
    "category": "Eventos",
    "views": 7932,
    "likes": 0,
    "comments": 8,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_70",
    "brand": "Hilton",
    "date": "2026-04-23",
    "title": "Dia de la madre",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 34500,
    "likes": 0,
    "comments": 9,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_71",
    "brand": "Hilton",
    "date": "2026-04-24",
    "title": "Dia de la madre",
    "format": "Carrusel",
    "category": "Otros",
    "views": 0,
    "likes": 0,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_72",
    "brand": "Hilton",
    "date": "2026-04-25",
    "title": "Noches de musica en vivo",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 0,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_73",
    "brand": "Hilton",
    "date": "2026-04-26",
    "title": "promos de feriado",
    "format": "Carrusel",
    "category": "Hospedaje",
    "views": 0,
    "likes": 0,
    "comments": 6,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_74",
    "brand": "Hilton",
    "date": "2026-04-27",
    "title": "Dia de la madre",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 170000,
    "likes": 0,
    "comments": 12,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_75",
    "brand": "Hilton",
    "date": "2026-04-28",
    "title": "Noches de musica en vivo",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 0,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_76",
    "brand": "Hilton",
    "date": "2026-04-29",
    "title": "Almuerzo Buffet para mamá",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 0,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_77",
    "brand": "Hilton",
    "date": "2026-04-29",
    "title": "Horarios de feriado - restaurantes",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 0,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_78",
    "brand": "Hilton",
    "date": "2026-05-01",
    "title": "Feliz Día del trabajo!",
    "format": "Reel",
    "category": "Otros",
    "views": 4381,
    "likes": 0,
    "comments": 7,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_79",
    "brand": "Hilton",
    "date": "2026-05-02",
    "title": "Dia de la madre - té buffet",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 0,
    "comments": 5,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_80",
    "brand": "Hilton",
    "date": "2026-05-03",
    "title": "Pool day - Colaboración",
    "format": "Reel",
    "category": "Hospedaje",
    "views": 5301,
    "likes": 0,
    "comments": 2,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_81",
    "brand": "Hilton",
    "date": "2026-05-03",
    "title": "Bar industria  convencion",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 4071,
    "likes": 93,
    "comments": 2,
    "shares": 72,
    "source": "Excel inicial"
  },
  {
    "id": "seed_hilton_82",
    "brand": "Hilton",
    "date": "2026-05-03",
    "title": "Menú día de la madre para llevar",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 69100,
    "likes": 0,
    "comments": 15,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_4",
    "brand": "Wyndham",
    "date": "2026-02-02",
    "title": "San valentin",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 39,
    "comments": 0,
    "shares": 14,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_5",
    "brand": "Wyndham",
    "date": "2026-02-06",
    "title": "Partido de la historia",
    "format": "Post",
    "category": "Hospedaje",
    "views": 0,
    "likes": 26,
    "comments": 0,
    "shares": 10,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_6",
    "brand": "Wyndham",
    "date": "2026-02-06",
    "title": "Promos para compartir - Lobby Bar",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 14,
    "comments": 0,
    "shares": 6,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_7",
    "brand": "Wyndham",
    "date": "2026-02-09",
    "title": "Carnaval",
    "format": "Post",
    "category": "Hospedaje",
    "views": 0,
    "likes": 38,
    "comments": 1,
    "shares": 6,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_8",
    "brand": "Wyndham",
    "date": "2026-02-10",
    "title": "Especiales del mes",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 90,
    "comments": 0,
    "shares": 13,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_9",
    "brand": "Wyndham",
    "date": "2026-02-10",
    "title": "Té time - Atardecer junto al río",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 31,
    "comments": 0,
    "shares": 7,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_10",
    "brand": "Wyndham",
    "date": "2026-02-11",
    "title": "Presentación del team",
    "format": "Reel",
    "category": "Otros",
    "views": 12500,
    "likes": 290,
    "comments": 26,
    "shares": 53,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_11",
    "brand": "Wyndham",
    "date": "2026-02-12",
    "title": "Hospedaje junto al río",
    "format": "Carrusel",
    "category": "Hospedaje",
    "views": 0,
    "likes": 176,
    "comments": 2,
    "shares": 55,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_12",
    "brand": "Wyndham",
    "date": "2026-02-13",
    "title": "Día de la margarita",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 22,
    "comments": 0,
    "shares": 6,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_13",
    "brand": "Wyndham",
    "date": "2026-02-14",
    "title": "Colaboradores - San Valentin",
    "format": "Reel",
    "category": "Otros",
    "views": 6030,
    "likes": 146,
    "comments": 1,
    "shares": 9,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_14",
    "brand": "Wyndham",
    "date": "2026-02-16",
    "title": "Preparacion cocteleria",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 2159,
    "likes": 56,
    "comments": 0,
    "shares": 5,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_15",
    "brand": "Wyndham",
    "date": "2026-02-16",
    "title": "Live music - Vol 2",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 13,
    "comments": 0,
    "shares": 6,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_16",
    "brand": "Wyndham",
    "date": "2026-02-17",
    "title": "Tradiciones en el puerto",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 41,
    "comments": 1,
    "shares": 20,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_17",
    "brand": "Wyndham",
    "date": "2026-02-21",
    "title": "Día de la margarita - Colab michael morales",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 2862,
    "likes": 82,
    "comments": 0,
    "shares": 6,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_18",
    "brand": "Wyndham",
    "date": "2026-02-24",
    "title": "Live music - Vol 3",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 11,
    "comments": 2,
    "shares": 4,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_19",
    "brand": "Wyndham",
    "date": "2026-02-26",
    "title": "Evento 593 mas travel",
    "format": "Reel",
    "category": "Eventos",
    "views": 3928,
    "likes": 47,
    "comments": 0,
    "shares": 3,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_20",
    "brand": "Wyndham",
    "date": "2026-03-02",
    "title": "Desayuno Buffet - Dia de la mujer",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 46,
    "comments": 0,
    "shares": 17,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_21",
    "brand": "Wyndham",
    "date": "2026-03-02",
    "title": "Almuerzo Buffet - Día de la mujer",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 23,
    "comments": 0,
    "shares": 1,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_22",
    "brand": "Wyndham",
    "date": "2026-03-04",
    "title": "Expectativa renovación de salones",
    "format": "Reel",
    "category": "Eventos",
    "views": 2908,
    "likes": 96,
    "comments": 0,
    "shares": 7,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_23",
    "brand": "Wyndham",
    "date": "2026-03-04",
    "title": "Miercoles de modo tasty",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 69,
    "comments": 5,
    "shares": 13,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_24",
    "brand": "Wyndham",
    "date": "2026-03-04",
    "title": "Remodelacion de salones de eventos",
    "format": "Reel",
    "category": "Eventos",
    "views": 2626,
    "likes": 1,
    "comments": 0,
    "shares": 9,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_25",
    "brand": "Wyndham",
    "date": "2026-03-05",
    "title": "Live music - Vol 3",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 14,
    "comments": 1,
    "shares": 8,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_26",
    "brand": "Wyndham",
    "date": "2026-03-08",
    "title": "Dia de la mujer - Colaboradores",
    "format": "Reel",
    "category": "Otros",
    "views": 2873,
    "likes": 146,
    "comments": 4,
    "shares": 6,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_27",
    "brand": "Wyndham",
    "date": "2026-03-09",
    "title": "Fanesca",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 54,
    "comments": 3,
    "shares": 18,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_28",
    "brand": "Wyndham",
    "date": "2026-03-11",
    "title": "Graduación",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 25,
    "comments": 0,
    "shares": 5,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_29",
    "brand": "Wyndham",
    "date": "2026-03-11",
    "title": "Live music - Vol 2",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 6,
    "comments": 0,
    "shares": 4,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_30",
    "brand": "Wyndham",
    "date": "2026-03-11",
    "title": "Remodelacion de salones de eventos",
    "format": "Reel",
    "category": "Eventos",
    "views": 10300,
    "likes": 122,
    "comments": 1,
    "shares": 12,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_31",
    "brand": "Wyndham",
    "date": "2026-03-11",
    "title": "Noches de puerto",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 38,
    "comments": 1,
    "shares": 13,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_32",
    "brand": "Wyndham",
    "date": "2026-03-11",
    "title": "Promos para compartir - Lobby Bar",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 32,
    "comments": 0,
    "shares": 2,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_33",
    "brand": "Wyndham",
    "date": "2026-03-12",
    "title": "Tradiciones en el puerto",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 19,
    "comments": 0,
    "shares": 3,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_34",
    "brand": "Wyndham",
    "date": "2026-03-13",
    "title": "Especiales del mes",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 17,
    "comments": 0,
    "shares": 1,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_35",
    "brand": "Wyndham",
    "date": "2026-03-13",
    "title": "Fanesca - Radio Wqradio",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 4099,
    "likes": 53,
    "comments": 2,
    "shares": 9,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_36",
    "brand": "Wyndham",
    "date": "2026-03-13",
    "title": "Fines de semana - Junto al Río",
    "format": "Post",
    "category": "Hospedaje",
    "views": 0,
    "likes": 11,
    "comments": 0,
    "shares": 4,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_37",
    "brand": "Wyndham",
    "date": "2026-03-13",
    "title": "Lobby Bar - cocteleria",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 2315,
    "likes": 47,
    "comments": 1,
    "shares": 5,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_38",
    "brand": "Wyndham",
    "date": "2026-03-14",
    "title": "Hospedaje junto al río",
    "format": "Carrusel",
    "category": "Hospedaje",
    "views": 0,
    "likes": 31,
    "comments": 0,
    "shares": 13,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_39",
    "brand": "Wyndham",
    "date": "2026-03-15",
    "title": "Fanesca - Cosas que pasan",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 120,
    "comments": 1,
    "shares": 22,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_40",
    "brand": "Wyndham",
    "date": "2026-03-16",
    "title": "Fanesca - Sintonizados streaming",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 1518,
    "likes": 20,
    "comments": 0,
    "shares": 4,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_41",
    "brand": "Wyndham",
    "date": "2026-03-16",
    "title": "Fanesca - Sintonizados streaming",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 2900,
    "likes": 74,
    "comments": 6,
    "shares": 39,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_42",
    "brand": "Wyndham",
    "date": "2026-03-18",
    "title": "Live music - Vol 3",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 11,
    "comments": 0,
    "shares": 1,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_43",
    "brand": "Wyndham",
    "date": "2026-03-24",
    "title": "Promo hospedaje para CVDL 2026",
    "format": "Post",
    "category": "Hospedaje",
    "views": 0,
    "likes": 10,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_44",
    "brand": "Wyndham",
    "date": "2026-03-24",
    "title": "Semana Santa Junto al río",
    "format": "Post",
    "category": "Hospedaje",
    "views": 0,
    "likes": 20,
    "comments": 1,
    "shares": 8,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_45",
    "brand": "Wyndham",
    "date": "2026-03-24",
    "title": "Live music - Vol 4",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 10,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_46",
    "brand": "Wyndham",
    "date": "2026-03-25",
    "title": "Fanesca",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 4282,
    "likes": 23,
    "comments": 0,
    "shares": 1,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_47",
    "brand": "Wyndham",
    "date": "2026-03-30",
    "title": "Instalaciones de los nuevos salones de eventos",
    "format": "Reel",
    "category": "Eventos",
    "views": 20300,
    "likes": 143,
    "comments": 2,
    "shares": 23,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_48",
    "brand": "Wyndham",
    "date": "2026-03-30",
    "title": "Woman forward 2026 evento",
    "format": "Reel",
    "category": "Eventos",
    "views": 4477,
    "likes": 160,
    "comments": 34,
    "shares": 8,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_49",
    "brand": "Wyndham",
    "date": "2026-03-31",
    "title": "Tarifa especial",
    "format": "Post",
    "category": "Hospedaje",
    "views": 0,
    "likes": 47,
    "comments": 0,
    "shares": 6,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_50",
    "brand": "Wyndham",
    "date": "2026-03-31",
    "title": "Live music - Vol 1",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 16,
    "comments": 1,
    "shares": 5,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_51",
    "brand": "Wyndham",
    "date": "2026-04-04",
    "title": "Salones de eventos",
    "format": "Carrusel",
    "category": "Eventos",
    "views": 0,
    "likes": 76,
    "comments": 0,
    "shares": 6,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_52",
    "brand": "Wyndham",
    "date": "2026-04-07",
    "title": "Live music - Vol 1",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 11,
    "comments": 0,
    "shares": 2,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_53",
    "brand": "Wyndham",
    "date": "2026-04-07",
    "title": "Hospedaje junto al río",
    "format": "Carrusel",
    "category": "Hospedaje",
    "views": 0,
    "likes": 42,
    "comments": 2,
    "shares": 36,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_54",
    "brand": "Wyndham",
    "date": "2026-04-07",
    "title": "Promos para compartir - Lobby Bar",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 17,
    "comments": 0,
    "shares": 4,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_55",
    "brand": "Wyndham",
    "date": "2026-04-07",
    "title": "Iniciativa Light it up blue",
    "format": "Carrusel",
    "category": "Otros",
    "views": 0,
    "likes": 61,
    "comments": 0,
    "shares": 1,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_56",
    "brand": "Wyndham",
    "date": "2026-04-08",
    "title": "Nota de forbes \"inversion en renovaciones",
    "format": "Post",
    "category": "Otros",
    "views": 0,
    "likes": 163,
    "comments": 1,
    "shares": 44,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_57",
    "brand": "Wyndham",
    "date": "2026-04-08",
    "title": "Remodelacion de salones - Radio Wqradio",
    "format": "Reel",
    "category": "Eventos",
    "views": 3970,
    "likes": 64,
    "comments": 4,
    "shares": 13,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_58",
    "brand": "Wyndham",
    "date": "2026-04-08",
    "title": "Remodelacion de salones - Radio Wqradio",
    "format": "Carrusel",
    "category": "Eventos",
    "views": 0,
    "likes": 114,
    "comments": 0,
    "shares": 14,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_59",
    "brand": "Wyndham",
    "date": "2026-04-09",
    "title": "Especiales del mes",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 21,
    "comments": 0,
    "shares": 4,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_60",
    "brand": "Wyndham",
    "date": "2026-04-09",
    "title": "Nominaciones en world travel awards",
    "format": "Carrusel",
    "category": "Otros",
    "views": 0,
    "likes": 42,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_61",
    "brand": "Wyndham",
    "date": "2026-04-09",
    "title": "Tu proxima celebracion Junto al río",
    "format": "Reel",
    "category": "Eventos",
    "views": 9522,
    "likes": 78,
    "comments": 1,
    "shares": 24,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_62",
    "brand": "Wyndham",
    "date": "2026-04-09",
    "title": "Instalaciones de wyhdham",
    "format": "Reel",
    "category": "Hospedaje",
    "views": 1780,
    "likes": 42,
    "comments": 2,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_63",
    "brand": "Wyndham",
    "date": "2026-04-09",
    "title": "Tradiciones en el puerto",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 12,
    "comments": 2,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_64",
    "brand": "Wyndham",
    "date": "2026-04-10",
    "title": "Experiencia - Lobby Bar",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 17,
    "comments": 0,
    "shares": 1,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_65",
    "brand": "Wyndham",
    "date": "2026-04-10",
    "title": "Lo nuevo de los salones",
    "format": "Reel",
    "category": "Eventos",
    "views": 3910,
    "likes": 79,
    "comments": 0,
    "shares": 10,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_66",
    "brand": "Wyndham",
    "date": "2026-04-13",
    "title": "Colaboracion con Nadia Mejia - Intalaciones del hotel",
    "format": "Reel",
    "category": "Hospedaje",
    "views": 142000,
    "likes": 7739,
    "comments": 198,
    "shares": 77,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_67",
    "brand": "Wyndham",
    "date": "2026-04-13",
    "title": "Promos para compartir - Lobby Bar",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 36,
    "comments": 5,
    "shares": 4,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_68",
    "brand": "Wyndham",
    "date": "2026-04-14",
    "title": "Live music - Vol 3",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 11,
    "comments": 0,
    "shares": 1,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_69",
    "brand": "Wyndham",
    "date": "2026-04-16",
    "title": "Nuevas intalaciones salones",
    "format": "Carrusel",
    "category": "Eventos",
    "views": 0,
    "likes": 43,
    "comments": 0,
    "shares": 3,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_70",
    "brand": "Wyndham",
    "date": "2026-04-16",
    "title": "Desayuno Buffet - Dia de la madre",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 96,
    "comments": 2,
    "shares": 50,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_71",
    "brand": "Wyndham",
    "date": "2026-04-18",
    "title": "Desayuno Buffet - Dia de la madre",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 53,
    "comments": 0,
    "shares": 34,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_72",
    "brand": "Wyndham",
    "date": "2026-04-18",
    "title": "Almuerzo Buffet - Día de la madre",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 58,
    "comments": 3,
    "shares": 53,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_73",
    "brand": "Wyndham",
    "date": "2026-04-20",
    "title": "Almuerzo Buffet - Día de la madre",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 40,
    "comments": 0,
    "shares": 25,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_74",
    "brand": "Wyndham",
    "date": "2026-04-20",
    "title": "Feriado Junto al Río",
    "format": "Post",
    "category": "Hospedaje",
    "views": 0,
    "likes": 28,
    "comments": 0,
    "shares": 8,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_75",
    "brand": "Wyndham",
    "date": "2026-04-21",
    "title": "Live music - Vol 4",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 10,
    "comments": 1,
    "shares": 5,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_76",
    "brand": "Wyndham",
    "date": "2026-04-24",
    "title": "Instalaciones de salón",
    "format": "Reel",
    "category": "Eventos",
    "views": 11900,
    "likes": 60,
    "comments": 0,
    "shares": 6,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_77",
    "brand": "Wyndham",
    "date": "2026-04-29",
    "title": "Día de la madre - Radio Wqradio",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 2793,
    "likes": 42,
    "comments": 0,
    "shares": 26,
    "source": "Excel inicial"
  },
  {
    "id": "seed_wyndham_78",
    "brand": "Wyndham",
    "date": "2026-04-29",
    "title": "Live music - Vol 1",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 14,
    "comments": 0,
    "shares": 4,
    "source": "Excel inicial"
  },
  {
    "id": "seed_sheraton_5",
    "brand": "Sheraton",
    "date": "2026-02-04",
    "title": "15 años - Eevento",
    "format": "Reel",
    "category": "Eventos",
    "views": 4596,
    "likes": 103,
    "comments": 5,
    "shares": 17,
    "source": "Excel inicial"
  },
  {
    "id": "seed_sheraton_6",
    "brand": "Sheraton",
    "date": "2026-02-04",
    "title": "San valentin",
    "format": "Reel",
    "category": "Hospedaje",
    "views": 3787,
    "likes": 60,
    "comments": 0,
    "shares": 5,
    "source": "Excel inicial"
  },
  {
    "id": "seed_sheraton_7",
    "brand": "Sheraton",
    "date": "2026-02-27",
    "title": "Fanesca",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 49,
    "comments": 2,
    "shares": 10,
    "source": "Excel inicial"
  },
  {
    "id": "seed_sheraton_8",
    "brand": "Sheraton",
    "date": "2026-03-04",
    "title": "Noche en pareja",
    "format": "Reel",
    "category": "Hospedaje",
    "views": 185000,
    "likes": 718,
    "comments": 20,
    "shares": 103,
    "source": "Excel inicial"
  },
  {
    "id": "seed_sheraton_9",
    "brand": "Sheraton",
    "date": "2026-03-06",
    "title": "Woman's Day",
    "format": "Reel",
    "category": "Otros",
    "views": 3357,
    "likes": 128,
    "comments": 0,
    "shares": 13,
    "source": "Excel inicial"
  },
  {
    "id": "seed_sheraton_10",
    "brand": "Sheraton",
    "date": "2026-03-10",
    "title": "Tarde de amigas (Cheer ladies)",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 2326,
    "likes": 29,
    "comments": 0,
    "shares": 3,
    "source": "Excel inicial"
  },
  {
    "id": "seed_sheraton_11",
    "brand": "Sheraton",
    "date": "2026-03-10",
    "title": "Escapada de fin de semana",
    "format": "Reel",
    "category": "Hospedaje",
    "views": 5531,
    "likes": 94,
    "comments": 1,
    "shares": 22,
    "source": "Excel inicial"
  },
  {
    "id": "seed_sheraton_12",
    "brand": "Sheraton",
    "date": "2026-03-16",
    "title": "Día Internacional del Whisky",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 22200,
    "likes": 106,
    "comments": 4,
    "shares": 2,
    "source": "Excel inicial"
  },
  {
    "id": "seed_sheraton_13",
    "brand": "Sheraton",
    "date": "2026-04-01",
    "title": "Eventos coorporativos",
    "format": "Reel",
    "category": "Eventos",
    "views": 54400,
    "likes": 185,
    "comments": 0,
    "shares": 6,
    "source": "Excel inicial"
  },
  {
    "id": "seed_sheraton_14",
    "brand": "Sheraton",
    "date": "2026-04-09",
    "title": "Tarde de mimosas & amigos",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 40200,
    "likes": 307,
    "comments": 10,
    "shares": 71,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_4",
    "brand": "Oro Verde",
    "date": "2026-02-02",
    "title": "Suite presidencial messi - forbes",
    "format": "Carrusel",
    "category": "Otros",
    "views": 0,
    "likes": 336,
    "comments": 14,
    "shares": 78,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_5",
    "brand": "Oro Verde",
    "date": "2026-02-02",
    "title": "expectativa messi",
    "format": "Reel",
    "category": "Otros",
    "views": 2380,
    "likes": 49,
    "comments": 1,
    "shares": 5,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_6",
    "brand": "Oro Verde",
    "date": "2026-02-03",
    "title": "Le Menu des Saveurs d’Amour - La fondou",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 61,
    "comments": 0,
    "shares": 13,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_7",
    "brand": "Oro Verde",
    "date": "2026-02-03",
    "title": "Tarde de té",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 32,
    "comments": 0,
    "shares": 7,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_8",
    "brand": "Oro Verde",
    "date": "2026-02-04",
    "title": "Almuerzo Buffet - Parrilada Argentina",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 81,
    "comments": 1,
    "shares": 49,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_9",
    "brand": "Oro Verde",
    "date": "2026-02-04",
    "title": "Desayuno Buffet de Campeones",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 23,
    "comments": 0,
    "shares": 1,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_10",
    "brand": "Oro Verde",
    "date": "2026-02-04",
    "title": "Rueda de prensa - El partido de la historia",
    "format": "Reel",
    "category": "Otros",
    "views": 7943,
    "likes": 179,
    "comments": 1,
    "shares": 13,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_11",
    "brand": "Oro Verde",
    "date": "2026-02-04",
    "title": "Almuerzo Buffet Parrillada Argentina",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 5754,
    "likes": 31,
    "comments": 0,
    "shares": 8,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_12",
    "brand": "Oro Verde",
    "date": "2026-02-05",
    "title": "Paquete - El partido de la Historia",
    "format": "Carrusel",
    "category": "Hospedaje",
    "views": 0,
    "likes": 26,
    "comments": 2,
    "shares": 1,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_13",
    "brand": "Oro Verde",
    "date": "2026-02-05",
    "title": "Taste of palms",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 11,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_14",
    "brand": "Oro Verde",
    "date": "2026-02-05",
    "title": "expectativa partido de la Historia",
    "format": "Reel",
    "category": "Hospedaje",
    "views": 39100,
    "likes": 163,
    "comments": 1,
    "shares": 11,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_15",
    "brand": "Oro Verde",
    "date": "2026-02-05",
    "title": "Fan Fest speakeasy",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 45,
    "comments": 0,
    "shares": 5,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_16",
    "brand": "Oro Verde",
    "date": "2026-02-05",
    "title": "Coctel \"la misma de siempre\"",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 3811,
    "likes": 51,
    "comments": 0,
    "shares": 6,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_17",
    "brand": "Oro Verde",
    "date": "2026-02-05",
    "title": "Paquete - El partido de la Historia",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 6653,
    "likes": 140,
    "comments": 1,
    "shares": 9,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_18",
    "brand": "Oro Verde",
    "date": "2026-02-05",
    "title": "Casa Oficial del Partido de la Historia,",
    "format": "Reel",
    "category": "Otros",
    "views": 3321,
    "likes": 75,
    "comments": 1,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_19",
    "brand": "Oro Verde",
    "date": "2026-02-06",
    "title": "ALMUERZO BUFFET PARRILLADA ARGENTINA",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 8598,
    "likes": 176,
    "comments": 0,
    "shares": 16,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_20",
    "brand": "Oro Verde",
    "date": "2026-02-06",
    "title": "Tarifas de feriado - Febrero",
    "format": "Carrusel",
    "category": "Hospedaje",
    "views": 0,
    "likes": 92,
    "comments": 0,
    "shares": 25,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_21",
    "brand": "Oro Verde",
    "date": "2026-02-06",
    "title": "Combo la misma de siempre",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 7171,
    "likes": 54,
    "comments": 0,
    "shares": 5,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_22",
    "brand": "Oro Verde",
    "date": "2026-02-06",
    "title": "Combo la misma de siempre",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 59,
    "comments": 0,
    "shares": 19,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_23",
    "brand": "Oro Verde",
    "date": "2026-02-06",
    "title": "Hospedate y vive la experiencia - messi",
    "format": "Reel",
    "category": "Hospedaje",
    "views": 6318,
    "likes": 145,
    "comments": 2,
    "shares": 4,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_24",
    "brand": "Oro Verde",
    "date": "2026-02-07",
    "title": "Cuando el fútbol hace historia, el lugar donde te hospedas importa.",
    "format": "Reel",
    "category": "Hospedaje",
    "views": 3085,
    "likes": 48,
    "comments": 2,
    "shares": 1,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_25",
    "brand": "Oro Verde",
    "date": "2026-02-07",
    "title": "Temporada del amor",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 2827,
    "likes": 6,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_26",
    "brand": "Oro Verde",
    "date": "2026-02-07",
    "title": "la casa oficial del partido de la historia.",
    "format": "Reel",
    "category": "Hospedaje",
    "views": 11600,
    "likes": 309,
    "comments": 3,
    "shares": 21,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_27",
    "brand": "Oro Verde",
    "date": "2026-02-09",
    "title": "Desayuno San Valentin",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 123,
    "comments": 0,
    "shares": 31,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_28",
    "brand": "Oro Verde",
    "date": "2026-02-09",
    "title": "Partido de la historia - dia del partido",
    "format": "Reel",
    "category": "Otros",
    "views": 3384,
    "likes": 107,
    "comments": 0,
    "shares": 11,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_29",
    "brand": "Oro Verde",
    "date": "2026-02-10",
    "title": "Graduacion",
    "format": "Reel",
    "category": "Eventos",
    "views": 221000,
    "likes": 85,
    "comments": 3,
    "shares": 5,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_30",
    "brand": "Oro Verde",
    "date": "2026-02-11",
    "title": "Cumpleaños",
    "format": "Reel",
    "category": "Eventos",
    "views": 105000,
    "likes": 356,
    "comments": 5,
    "shares": 46,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_31",
    "brand": "Oro Verde",
    "date": "2026-02-11",
    "title": "cena Buffet - san valentin",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 3643,
    "likes": 37,
    "comments": 0,
    "shares": 4,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_32",
    "brand": "Oro Verde",
    "date": "2026-02-12",
    "title": "escapada para celebrar el amor",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 2855,
    "likes": 48,
    "comments": 0,
    "shares": 4,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_33",
    "brand": "Oro Verde",
    "date": "2026-02-12",
    "title": "Temporada del amor",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 7585,
    "likes": 248,
    "comments": 7,
    "shares": 11,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_34",
    "brand": "Oro Verde",
    "date": "2026-02-14",
    "title": "Desayuno  Buffet",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 2064,
    "likes": 29,
    "comments": 0,
    "shares": 1,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_35",
    "brand": "Oro Verde",
    "date": "2026-02-15",
    "title": "Almuerzo Buffet",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 2360,
    "likes": 31,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_36",
    "brand": "Oro Verde",
    "date": "2026-02-18",
    "title": "Promo Graduado",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 57,
    "comments": 24,
    "shares": 12,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_37",
    "brand": "Oro Verde",
    "date": "2026-02-18",
    "title": "Fanesca",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 61000,
    "likes": 276,
    "comments": 7,
    "shares": 13,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_38",
    "brand": "Oro Verde",
    "date": "2026-02-21",
    "title": "Desayuno buffet el patio",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 27,
    "comments": 0,
    "shares": 4,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_39",
    "brand": "Oro Verde",
    "date": "2026-02-23",
    "title": "fanesca",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 258000,
    "likes": 80,
    "comments": 4,
    "shares": 5,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_40",
    "brand": "Oro Verde",
    "date": "2026-02-24",
    "title": "Dia del Bartender",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 3893,
    "likes": 73,
    "comments": 5,
    "shares": 8,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_41",
    "brand": "Oro Verde",
    "date": "2026-02-27",
    "title": "Graduacion - Eventos de oro",
    "format": "Reel",
    "category": "Eventos",
    "views": 8634,
    "likes": 329,
    "comments": 13,
    "shares": 20,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_42",
    "brand": "Oro Verde",
    "date": "2026-03-01",
    "title": "Día de la Mujer - Agenda",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 43,
    "likes": 414,
    "comments": 1,
    "shares": 5,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_43",
    "brand": "Oro Verde",
    "date": "2026-03-03",
    "title": "Oro verde rewards",
    "format": "Carrusel",
    "category": "Hospedaje",
    "views": 0,
    "likes": 19,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_44",
    "brand": "Oro Verde",
    "date": "2026-03-03",
    "title": "El capitan - cocteleria - sushi",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 21,
    "comments": 1,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_45",
    "brand": "Oro Verde",
    "date": "2026-03-05",
    "title": "Foro equidad de genero",
    "format": "Post",
    "category": "Otros",
    "views": 0,
    "likes": 19,
    "comments": 4,
    "shares": 5,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_46",
    "brand": "Oro Verde",
    "date": "2026-03-08",
    "title": "Día de la mujer",
    "format": "Post",
    "category": "Otros",
    "views": 3605,
    "likes": 116,
    "comments": 0,
    "shares": 5,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_47",
    "brand": "Oro Verde",
    "date": "2026-03-08",
    "title": "Mejor plan oro verde",
    "format": "Reel",
    "category": "Hospedaje",
    "views": 9332,
    "likes": 122,
    "comments": 3,
    "shares": 11,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_48",
    "brand": "Oro Verde",
    "date": "2026-03-09",
    "title": "reserva tu evento",
    "format": "Post",
    "category": "Eventos",
    "views": 0,
    "likes": 36,
    "comments": 0,
    "shares": 4,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_49",
    "brand": "Oro Verde",
    "date": "2026-03-11",
    "title": "especial de mariscos",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 5500,
    "comments": 0,
    "shares": 8,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_50",
    "brand": "Oro Verde",
    "date": "2026-03-11",
    "title": "especial de mariscos",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 27100,
    "likes": 186,
    "comments": 9,
    "shares": 71,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_51",
    "brand": "Oro Verde",
    "date": "2026-03-13",
    "title": "Tarifas especiales - marzo",
    "format": "Carrusel",
    "category": "Hospedaje",
    "views": 0,
    "likes": 66,
    "comments": 2,
    "shares": 7,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_52",
    "brand": "Oro Verde",
    "date": "2026-03-14",
    "title": "El Patio -  nuevo plato",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 30,
    "comments": 3,
    "shares": 1,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_53",
    "brand": "Oro Verde",
    "date": "2026-03-15",
    "title": "Graduacion",
    "format": "Reel",
    "category": "Eventos",
    "views": 4529,
    "likes": 92,
    "comments": 0,
    "shares": 2,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_54",
    "brand": "Oro Verde",
    "date": "2026-03-15",
    "title": "reserva tu evento",
    "format": "Post",
    "category": "Eventos",
    "views": 0,
    "likes": 17,
    "comments": 0,
    "shares": 1,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_55",
    "brand": "Oro Verde",
    "date": "2026-03-15",
    "title": "Desayuno Buffet - el patio",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 13,
    "comments": 0,
    "shares": 5,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_56",
    "brand": "Oro Verde",
    "date": "2026-03-16",
    "title": "Almuerzo Buffet",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 1935,
    "likes": 20,
    "comments": 0,
    "shares": 6,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_57",
    "brand": "Oro Verde",
    "date": "2026-03-16",
    "title": "Velada de Jazz & Vino en Le Gourmet",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 111,
    "comments": 0,
    "shares": 23,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_58",
    "brand": "Oro Verde",
    "date": "2026-03-18",
    "title": "Viernes de Mariscos en Le Gourmet",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 101,
    "comments": 3,
    "shares": 3,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_59",
    "brand": "Oro Verde",
    "date": "2026-03-19",
    "title": "Combo shawarma",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 25,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_60",
    "brand": "Oro Verde",
    "date": "2026-03-19",
    "title": "Viernes de Mariscos en Le Gourmet",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 7988,
    "likes": 48,
    "comments": 2,
    "shares": 15,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_61",
    "brand": "Oro Verde",
    "date": "2026-03-19",
    "title": "El capitan - cocteleria - sushi",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 14400,
    "likes": 69,
    "comments": 4,
    "shares": 7,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_62",
    "brand": "Oro Verde",
    "date": "2026-03-21",
    "title": "Fanesca",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 9163,
    "likes": 122,
    "comments": 5,
    "shares": 7,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_63",
    "brand": "Oro Verde",
    "date": "2026-03-21",
    "title": "Coctel del mes: habla, mandarina",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 23,
    "comments": 0,
    "shares": 1,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_64",
    "brand": "Oro Verde",
    "date": "2026-03-22",
    "title": "reserva tu evento",
    "format": "Post",
    "category": "Eventos",
    "views": 0,
    "likes": 14,
    "comments": 0,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_65",
    "brand": "Oro Verde",
    "date": "2026-03-24",
    "title": "Dirección de Turismo y Eventos Especiales",
    "format": "Reel",
    "category": "Otros",
    "views": 2853,
    "likes": 0,
    "comments": 1,
    "shares": 0,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_66",
    "brand": "Oro Verde",
    "date": "2026-03-25",
    "title": "Dia del Waflle",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 2539,
    "likes": 20,
    "comments": 0,
    "shares": 9,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_67",
    "brand": "Oro Verde",
    "date": "2026-03-26",
    "title": "Vive cada partido de La Tri en el Bar El Capitán",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 7326,
    "likes": 130,
    "comments": 2,
    "shares": 10,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_68",
    "brand": "Oro Verde",
    "date": "2026-03-30",
    "title": "Fanesca",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 61,
    "comments": 8,
    "shares": 14,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_69",
    "brand": "Oro Verde",
    "date": "2026-03-31",
    "title": "Festival oro verde manta",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 14000,
    "likes": 132,
    "comments": 2,
    "shares": 14,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_70",
    "brand": "Oro Verde",
    "date": "2026-04-01",
    "title": "Vive una escaoada",
    "format": "Reel",
    "category": "Hospedaje",
    "views": 10100,
    "likes": 96,
    "comments": 0,
    "shares": 8,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_71",
    "brand": "Oro Verde",
    "date": "2026-04-02",
    "title": "Fanesca",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 9590,
    "likes": 274,
    "comments": 6,
    "shares": 25,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_72",
    "brand": "Oro Verde",
    "date": "2026-04-02",
    "title": "pascuas",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 3076,
    "likes": 43,
    "comments": 0,
    "shares": 17,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_73",
    "brand": "Oro Verde",
    "date": "2026-04-03",
    "title": "Fanesca - forbes",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 5073,
    "likes": 51,
    "comments": 1,
    "shares": 6,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_74",
    "brand": "Oro Verde",
    "date": "2026-04-04",
    "title": "Festival manaba",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 57,
    "comments": 2,
    "shares": 12,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_75",
    "brand": "Oro Verde",
    "date": "2026-04-05",
    "title": "Eventos de oro",
    "format": "Reel",
    "category": "Eventos",
    "views": 255000,
    "likes": 216,
    "comments": 11,
    "shares": 12,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_76",
    "brand": "Oro Verde",
    "date": "2026-04-05",
    "title": "Expetativa renovacion de salon",
    "format": "Post",
    "category": "Eventos",
    "views": 0,
    "likes": 75,
    "comments": 0,
    "shares": 8,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_77",
    "brand": "Oro Verde",
    "date": "2026-04-05",
    "title": "fanesca",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 20,
    "comments": 0,
    "shares": 3,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_78",
    "brand": "Oro Verde",
    "date": "2026-04-07",
    "title": "Mama vae oro",
    "format": "Post",
    "category": "Gastronomía",
    "views": 0,
    "likes": 134,
    "comments": 12,
    "shares": 64,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_79",
    "brand": "Oro Verde",
    "date": "2026-04-08",
    "title": "Planes de Abril",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 196,
    "comments": 2,
    "shares": 7,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_80",
    "brand": "Oro Verde",
    "date": "2026-04-09",
    "title": "La Fondue",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 67500,
    "likes": 904,
    "comments": 23,
    "shares": 90,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_81",
    "brand": "Oro Verde",
    "date": "2026-04-10",
    "title": "Los viernes se viven diferente en Bar El Capitán",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 13900,
    "likes": 59,
    "comments": 1,
    "shares": 8,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_82",
    "brand": "Oro Verde",
    "date": "2026-04-10",
    "title": "Festival manaba",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 11700,
    "likes": 194,
    "comments": 2,
    "shares": 52,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_83",
    "brand": "Oro Verde",
    "date": "2026-04-12",
    "title": "Día del Sánduche",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 5131,
    "likes": 70,
    "comments": 2,
    "shares": 4,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_84",
    "brand": "Oro Verde",
    "date": "2026-04-13",
    "title": "rewards - Mama vale oro",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 25,
    "comments": 0,
    "shares": 1,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_85",
    "brand": "Oro Verde",
    "date": "2026-04-13",
    "title": "Tarifas Especiales",
    "format": "Carrusel",
    "category": "Hospedaje",
    "views": 0,
    "likes": 29,
    "comments": 0,
    "shares": 8,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_86",
    "brand": "Oro Verde",
    "date": "2026-04-14",
    "title": "Menu -Mama de oro",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 62,
    "comments": 4,
    "shares": 17,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_87",
    "brand": "Oro Verde",
    "date": "2026-04-15",
    "title": "habitaciones renovadas",
    "format": "Reel",
    "category": "Hospedaje",
    "views": 30700,
    "likes": 114,
    "comments": 6,
    "shares": 9,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_88",
    "brand": "Oro Verde",
    "date": "2026-04-16",
    "title": "Especial de Mariscos en Le Gourmet",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 3047,
    "likes": 55,
    "comments": 2,
    "shares": 13,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_89",
    "brand": "Oro Verde",
    "date": "2026-04-16",
    "title": "Los viernes se viven diferente en Bar El Capitán",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 28,
    "comments": 0,
    "shares": 2,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_90",
    "brand": "Oro Verde",
    "date": "2026-04-21",
    "title": "Almuerzo buffet bailable - mama vale oro",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 65,
    "comments": 0,
    "shares": 20,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_91",
    "brand": "Oro Verde",
    "date": "2026-04-22",
    "title": "Almuerzo buffet - mama vale oro",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 66,
    "comments": 0,
    "shares": 14,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_92",
    "brand": "Oro Verde",
    "date": "2026-04-28",
    "title": "Mama vale oro",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 17,
    "comments": 0,
    "shares": 10,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_93",
    "brand": "Oro Verde",
    "date": "2026-04-28",
    "title": "Mamá Vale Oro - Golden Mom Party",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 46100,
    "likes": 159,
    "comments": 3,
    "shares": 22,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_94",
    "brand": "Oro Verde",
    "date": "2026-04-29",
    "title": "Mama vale oro - Banquete de Reinas",
    "format": "Reel",
    "category": "Gastronomía",
    "views": 2313,
    "likes": 21,
    "comments": 2,
    "shares": 5,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_95",
    "brand": "Oro Verde",
    "date": "2026-04-29",
    "title": "Mama vale oro - Agenda",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 44,
    "comments": 0,
    "shares": 42,
    "source": "Excel inicial"
  },
  {
    "id": "seed_oro_verde_96",
    "brand": "Oro Verde",
    "date": "2026-04-30",
    "title": "Mama vale oro",
    "format": "Carrusel",
    "category": "Gastronomía",
    "views": 0,
    "likes": 39,
    "comments": 4,
    "shares": 26,
    "source": "Excel inicial"
  }
];
